"""
Django settings for chimen project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from .base import *


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ce+@ad+eir$37550+(#pmkjct(dlziewi_xkm#7xrauaxs)vb@'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = []


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
DATABASE_PASSWORD = 'Chimen2021'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'chimen',
        'USER': 'chimenAdmin',
        'PASSWORD': DATABASE_PASSWORD,
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Email
# https://docs.djangoproject.com/en/3.2/ref/settings/#email
# https://docs.djangoproject.com/en/2.2/topics/email/
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'chimen.akamon@gmail.com'
EMAIL_HOST_PASSWORD = 'vxqjixenpsbhwnas'
#EMAIL_SUBJECT_PREFIX = ''
EMAIL_USE_TLS = True
